# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'NPaySDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#install_all_flutter_pods(flutter_application_path)
  # Pods for NPaySDKDemo

end
